### ISSUE TITLE
GoutteDriver / Submitting when there are many submit buttons

### ISSUE THREAD

**Issue by fvilpoix** [minkphp/Mink#212]
Hello,

I have similar issue than #209 and #100 but I don't know if it comes from the same error. If I try to press one of many submit buttons, it always take the first one value, and not the good one (even if I press with id). I think it comes from 
https://github.com/Behat/Mink/blob/master/src/Behat/Mink/Driver/GoutteDriver.php#L547

```
if (isset($this->forms[$formId])) {
  return $this->forms[$formId][$fieldName];
}
```

Maybe it would be a good idea to store data by field id and not by field name.

How to reproduce :

mink.html

```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML+RDFa 1.0//EN"
  "http://www.w3.org/MarkUp/DTD/xhtml-rdfa-1.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<body>
  <form action="/" method="post" id="user-login-form">
    <input type="submit" name="toto" id="jaguar-button" value="jaguar"/>
    <input type="submit" name="toto" id="poney-button" value="poney"/>
  </form>
</body>
</html>

```

```
<?php
// mink_usecase.php
require_once('vendor/mink.phar');

use \Behat\Mink\PHPUnit\TestCase;

class MinkTest extends TestCase
{
  public function testMink(){
    $url = 'http://localhost/mink.html';

    $session = $this->getSession('goutte');
    $session->visit($url);
    $page = $session->getPage();

    $node_field = $page->findById('poney-button');
    $this->assertEquals('poney', $node_field->getValue(), 'ok');
  }
}
```

```
$ phpunit mink_usecase.php 
PHPUnit 3.6.10 by Sebastian Bergmann.

F

Time: 0 seconds, Memory: 11.50Mb

There was 1 failure:

1) MinkTest::testMink
ok
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'poney'
+'jaguar'

[...]/mink_usecase.php:16

FAILURES!
Tests: 1, Assertions: 1, Failures: 1.
```

The same happens if you try to press the second button, it will press the first one.

Thanks !

**Comment by SanjeewaMOHC** [comment]
Hi 
Any body know how to change the button value (value="Save profile") ???
I need to change it as "value =Save"

Please help me 
Thanks

<form id="commerce-addressbook-customer-profile-form" class="overlay-processed" accept-charset="UTF-8" method="post" action="/user/159/addressbook/shipping/edit/189?render=overlay&render=overlay">
<div>
<div id="edit-commerce-customer-address" class="field-type-addressfield field-name-commerce-customer-address field-widget-addressfield-standard form-wrapper">
<input type="hidden" value="form-usCiuM3Lud51NaqbxmnDtY17N6ADPLwLuL7XkIsmMlM" name="form_build_id">
<input type="hidden" value="Jpd1DdBzQLIn-HK6f9FBv9G-iF_n0LtqG1F0D6xDCsM" name="form_token">
<input type="hidden" value="commerce_addressbook_customer_profile_form" name="form_id">
<div id="edit-actions" class="form-actions form-wrapper">
<input id="edit-submit" class="form-submit" type="submit" value="Save profile" name="op">
</div>

**Comment by aik099** [comment]
Changing button value is not what user can do on the page. Usually it can be done via javascript, but Goutte driver doesn't support it.

**Comment by SanjeewaMOHC** [comment]
function MYTHEME_form_commerce_addressbook_customer_profile_form_alter(&$form, &$form_state, $form_id){
  $form['actions']['submit']['#value'] = t('Post Comments');
}

Do you know why this code doesn't work ?
Thanks

**Comment by stof** [comment]
@SanjeewaMOHC look at the generated HTML to see how it looks like. And it does not look like what you expect, contact the Drupal community.

**Comment by SanjeewaMOHC** [comment]
Thanks @stof
