### ISSUE TITLE
Improved window handling

### ISSUE THREAD

**Issue by aik099** [minkphp/Mink#338]
Mink already have several methods for working with windows, e.g. `resizeWindow` and `switchToWindow`. Both methods accept window name, but where do I get this name from?

If window was opened when clicking at `<a href="http://some-url" target="_blank">...</a>` link, then it don't have a name, that parent window would know about.

Also if focus was moved to popup window, then there is no way to return to parent window.

I'm proposing to add following methods to `CoreDriver`:
- `getWindowNames` - return names of all opened windows (can be done through `window_handles` class for `Selenium2Driver`)
- `getWindowName` - return name of currently active window (can be done through `window_handle` class for `Selenium2Driver`)

**Comment by durgesh1189** [comment]
I recently faced this issue, above @pthurmond's comments resolved my problem. But I did it manually by adding those functions in my files(mentioned above). How to get updated files by default?

**Comment by durgesh1189** [comment]
@stof could you please guide how to get those methods by default instead of adding manually in those files. Or please share mink version and selenium2 library versions in which these methods comes by default.

**Comment by stof** [comment]
Well, these methods are part of MinkSelenium2Driver 1.2.0 and Mink 1.6.0 (and so available in all newer releases).
