### ISSUE TITLE
Documentation problems

### ISSUE THREAD

**Issue by ftrotter** [minkphp/Mink#522]
First let me admit that I am new to css selectors, Xpath selectors, and Mink. With that said, please consider adding full examples to your documentation page. 

What you have now is "half" examples. Take, for instance the following section which is intended to explain find.
```
$fieldElement = $page->find('named',
    array('field', 'id|name|value|label')
);
$elementByCss = $page->find('css', 'h3 > a');
```

When I use the find function, do I always use 'named' as the first argument?
the second argument is clearly array. Do I use actual name "field" or do I replace that value with the field I am interested in? in the second element, do I use the strings 'id' or 'name' or 'value' or 'label', or do I replace them with the actual id, name, value, label that I am looking for? Using the actual string 'id|name|value|label' seems obviously wrong. Why would you have a value in your documentation that requires "mental parsing psuedo code". I don't think in the same psuedo code you do. So I am wondering if that is real code, that has does magical things or if its psuedo code and I am supposed to know what actually goes there. 

The second css selector uses a css selector (for which I can find plenty of documentation elsewhere) that obviously have nothing to do with the first "find" function. 

It would be nice to have a simple cheatsheet of css, named, shortcut functions and xpath equivalents for fairly straight forward things. i.e. given a standard link, how do you find things by id, name href or the text of the link? Same thing for buttons and other common form elements. Just three examples of the same html element found with all of the various selectors would do worlds to clarify the simplest way to get a particular task done. 

I know it must seem obvious to the reader how these things work. But the "named selector" functionality is Mink only. It has no external source of documentation like css and xpath do, but it seems simpler and easier to use. 

Also, just wondering why there is no findByName shortcut like there is a findById. I have some really funky names and ids (with colons in them) and not having to learn how to "escape" in Mink css, or in xpath makes my life much easier. 

Thanks for the very useful project.

-FT

**Comment by stof** [comment]
Closing because the doc is getting updated in https://github.com/minkphp/docs/pull/50 now
