### ISSUE TITLE
Case insensitive cookie handling

### ISSUE THREAD

**Issue by zebroc** [minkphp/Mink#598]
In our continuos integration we had the following situation:

base_url = http://HOSTNAME  <-- upper case

which broke the behat tests we were doing, because the webserver / app returned the cookies with a hostname of 'hostname' (lowercase)

As RFCs 2965 and 2109 state that domain / hostname / ip comparisons shall be case-insensitive, I think this should definitely be fixed here, regardless of what the underlying package returns.
(This should probably also fixed in Symfony/Browserkit, i.e. always return lowercase hostnames)

Let me know if you agree and I am happy to provide a patch.

**Comment by aik099** [comment]
@zebroc , is this still an issue?

Is the actual HTTP request to website made using uppercased domain as you mentioned or it's also lowercased. I suspect that HTTP request might be made to lowercased domain and that results in same lowercased domain used for cooking operations.

**Comment by zebroc** [comment]
I don't know but since we worked around it, it seems it's not a big issue.

Like I said/RFC-quoted: Host- and Domain names should never be treated case sensitive so it shouldn't matter how the original request is cased.

From my side, this can be closed since I have not worked on this in almost a year now but I guess the problem itself is probably still there.

**Comment by aik099** [comment]
I've tried to reproduce it locally by using `http://LOCALHOST` as hostname, but all tests (including cookie-related) passed.

**Comment by zebroc** [comment]
Hm, maybe this has been adressed in the meantime?

I have to admit I haven't worked in the environment for a few months now
anyway.

2015-07-03 22:09 GMT+02:00 Alexander Obuhovich <notifications@github.com>:

**Comment by aik099** [comment]
Who knows, maybe there was a fix in BrowserKit. Closing as non-reproducible then. Feel free to reopen if you'll encounter this in future.
