### ISSUE TITLE
Why isn't Mink waiting for elements like Capybara?

### ISSUE THREAD

**Issue by MPV** [minkphp/Mink#606]
We find ourselves writing all sorts of spin functions in our own Mink code — but I wonder:

##### Why isn't this built-in, like how Capybara does it?

> Capybara has a had a very important feature since pretty much the beginning which is that it automatically waits for elements to appear or disappear on the page. If you do something like find("#foo"), this will block until an element with id "foo" appears on the page, as will has_content?("bar"), click_link("baz") and most other things you can do with Capybara.
— http://www.elabs.se/blog/53-why-wait_until-was-removed-from-capybara

Caveat: 
We're still on Mink 1.4.3 — has this improved in newer versions?

**Comment by aik099** [comment]
I recommend using some wrapper around the Mink, like QA-Tools (see http://www.qa-tools.io/) which has this feature build-in. It will also allow you to move out element locators into dedicated classes to avoid duplication in tests.
