### ISSUE TITLE
How to use with zombie?

### ISSUE THREAD

**Issue by BevanR** [minkphp/Mink#615]
Mink suggests to use `behat/mink-zombie-driver` for a "fast and JS-enabled headless driver for any app (requires node.js)".  However I could not find a way to use Zombie with Behat instead of Selenium or Goutte.  Is there any documentation?

I also opened https://github.com/Behat/MinkZombieDriver/issues/115

**Comment by stof** [comment]
Well, there is a suggestion in the composer.json because Mink requires using one of its driver to instantiate the session.
