### ISSUE TITLE
`Behat\MinkExtensions\Extension` extension file or class could not be located.

### ISSUE THREAD

**Issue by Pkallesoe** [minkphp/Mink#625]
The error msg:

```
PHP Deprecated:  The ability to pass file names to Yaml::parse() was deprecated in 2.7
and will be removed in 3.0. Please, pass the contents of the file instead. in 
home/user/projects/php/projectname/vendor/symfony/yaml/Symfony/Component/Yaml/Yaml.php
on line 58

[Behat\Testwork\ServiceContainer\Exception\ExtensionInitializationException]    
`Behat\MinkExtensions\Extension` extension file or class could not be located. 
```

My composer.json:

```
"require": {
    "laravel/framework": "4.2.*",
    "behat/behat": "~3.0.6",
    "behat/mink": "1.6.*",                                                 
    "behat/mink-goutte-driver": "*",
    "behat/mink-selenium-driver": "*",
    "behat/mink-selenium2-driver": "*",
    "behat/mink-sahi-driver": "*",
    "behat/mink-zombie-driver": "*"
```

My behat.yml (located in the root of the project)

```
default:
    extensions:
        Behat\MinkExtensions\Extension:
            goutte: ~
```

I've tried different versions, but still same error msg. (No errors if I run it without a behat.yml file)

The commands I've run are:

```
./vendor/bin/behat --init
./vendor/bin/behat
```

But produces same msg.

**Comment by charu-jain** [comment]
I am getting same error and unable to find particular reason.

`C:\Behat>behat -version
  [Behat\Testwork\ServiceContainer\Exception\ExtensionInitializationException]
  `Behat\MinkExtension\Extension` extension file or class could not be `located.

Here is behat.yaml
`default:
  context:
    class: 'ProfilerContext'
    parameters:
        base_url: 'https://angular2.maialearning.com/#'

  paths:
    features: features
    bootstrap: features/bootstrap

  extensions:
    Behat\MinkExtension\Extension:
      selenium2: ~
      goutte: ~

chrome:
  extensions:
    Behat\MinkExtension\Extension:
      javascript_session: selenium2
      browser_name: chrome

firefox:
  extensions:
    Behat\MinkExtension\Extension:
      browser_name: firefox
`
This is composer.jason
`{
    "require": {
        "behat/behat": "~3.3.1",
        "behat/mink": "~1.5",
        "behat/mink-extension": "^2.2",
        "behat/mink-goutte-driver": "~1.0.8",
        "behat/mink-selenium2-driver": "~1.1.1"
    },
   "config": {
     "bin-dir": "bin/"
   }
}
`

**Comment by stof** [comment]
please read the documentation in the link given in the comment just before yours. `Behat\MinkExtension\Extension` is the wrong key for the extension (which is why it cannot be located). You should be using `Behat\MinkExtension`

**Comment by charu-jain** [comment]
Now when i modified the key, i am getting following error
`C:\Behat>behat -version
  [Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]
  Unrecognized options "context, paths" under "testwork"`

**Comment by stof** [comment]
Well, it looks like you have a config file written for Behat 2 and you are trying to use it with Behat 3. this won't work. but the Mink repo is the wrong place to ask for support.

**Comment by charu-jain** [comment]
Ohh.. right. Got it. Thanks. Changing behat and mink version worked.
`{
    "require": {
        "behat/behat": "~2.4.5",
        "behat/mink": "~1.5",
        "behat/mink-extension": "~1.1.4",
        "behat/mink-goutte-driver": "~1.0.8",
        "behat/mink-selenium2-driver": "~1.1.1"
    },
   "config": {
     "bin-dir": "bin/"
   }
}
`

**Comment by stof** [comment]
Note that Behat 2 is not maintained anymore though
