### ISSUE TITLE
Make "Scrutinizer CI" fail the build if new issues are found

### ISSUE THREAD

**Issue by aik099** [minkphp/Mink#628]
Right now (after Scrutinizer CI no longer fails the build based on Travis CI) it's become more obvious that coding standard violations should mark build as failed.

To make this happen following needs to be added to repository config on Scrutinizer CI website (for this repository and each driver repository):

``` yaml
build_failure_conditions:
    - 'issues.new.exists'
```

**Comment by stof** [comment]
here is how Scrutinizer looks when meeting a build failure: https://scrutinizer-ci.com/g/minkphp/Mink/inspections/89806a4c-fd0e-4049-9fba-0b8d5e6df7ac
and it sets the github status to failure

**Comment by aik099** [comment]
OK.

**Comment by aik099** [comment]
> https://github.com/minkphp/Mink/issues/628#issuecomment-68431538

@stof , has this (config for all drivers updated to support bailing the build) happened?

**Comment by stof** [comment]
@aik099 not done by me yet.
