### ISSUE TITLE
WebAssert (and getPage) should be able to dive into xml documents too

### ISSUE THREAD

**Issue by docteurklein** [minkphp/Mink#649]
As (not really) discussed in #408, it should be possible to query something else than `//html`-prefixed xpath queries.

I have a working diff here and wanted to know if you'd be interested in looking at it.

Cheers!

**Comment by aik099** [comment]
I guess the web page you're opening returns XML with proper XML content type. Are you sure, that drivers of Mink even support traversing through such non HTML document?

**Comment by docteurklein** [comment]
I have to admit I just tried with the symfony DomCrawler.

**Comment by aik099** [comment]
Please check the other drivers as well.

**Comment by aik099** [comment]
IMO using browser controller (which is Mink) to verify XML document content is incorrect. You can just curl document content and use DomCrawler on it.

**Comment by docteurklein** [comment]
@aik099 I see and agree. Mink as a whole is browser oriented. but if you look at the `WebAssert` api, it's mainly about DOM node assertions, which is a perfect fit for xml documents too.

**Comment by aik099** [comment]
The `WebAssert` API is not a standalone component I'm afraid and therefore you can't use it without using Mink itself.

**Comment by stof** [comment]
I agree with @aik099 here. This seems out of the scope of Mink.

and WebAssert does not perform assertions based on the DOM. It performs assertions on top of other parts of the Mink API (in initial versions of Mink, this layer was not there and assertions were implemented in consumers of Mink).
