### ISSUE TITLE
Named selector button don't look for input type= reset

### ISSUE THREAD

**Issue by iuriag** [minkphp/Mink#651]
The named selector "button" , don't  look the input type reset.

**Comment by aik099** [comment]
Are you sure you're using latest Mink version?

This was fixed some time ago. See https://github.com/minkphp/Mink/blob/master/src/Selector/NamedSelector.php#L44

**Comment by aik099** [comment]
@iuriag , ping.

**Comment by stof** [comment]
Closing as no response was provided and this was already fixed a while ago
