### ISSUE TITLE
bug when click on button that appears after hove

### ISSUE THREAD

**Issue by gamretsky** [minkphp/Mink#653]
Hello! Is it bug or I'm doing something wrong. In my scenario, which uses selenium driver, I need to click on button that appears after hover. I make:

<code>$session = $this->getSession();</code>
<code>$element = $session->getPage()->find('css', $locator);</code>
<code>$element->mouseOver();</code>
<code>//        sleep(2);</code>
<code>$clickElement = $session->getPage()->find('css', $locatorForClick);</code>
<code>var_dump($clickElement->isVisible());</code>
 <code>$clickElement->click();</code>

var_dump shows that element is visible but on click error i thrown:  "element not visible"

**Comment by aik099** [comment]
So, the `$clickElement` can be clicked but isn't detected as visible?

**Comment by gamretsky** [comment]
it's detected as visible but cannot be clicked.

<code>│ bool(true)</code>
      │ 
<code>element not visible
        (Session info: chrome=42.0.2311.152)
        (Driver info: chromedriver=2.9.248304,platform=Linux 3.16.0-37-generic x86_64) (WARNING: The server did not provide any stacktrace information)
      Command duration or timeout: 19 milliseconds
      Build info: version: '2.45.0', revision: '5017cb8', time: '2015-02-26 23:59:50'
      System info: host: 'gamretsky-nb', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.16.0-37-generic', java.version: '1.7.0_79'
      Session ID: 0eea66b725cd32b7dbca45f4d22342a2
      Driver info: org.openqa.selenium.chrome.ChromeDriver
      Capabilities [{platform=LINUX, acceptSslCerts=true, javascriptEnabled=true, browserName=chrome, chrome={userDataDir=/tmp/.com.google.Chrome.auBKl9}, rotatable=false, locationContextEnabled=true, version=42.0.2311.152, takesHeapSnapshot=true, cssSelectorsEnabled=true, databaseEnabled=false, handlesAlerts=true, browserConnectionEnabled=false, webStorageEnabled=true, nativeEvents=true, applicationCacheEnabled=false, takesScreenshot=true}] (WebDriver\Exception\ElementNotVisible)</code>

var_dump detects element as visible but when click is applied element is not visible. Maybe that's because second action doesn't start from endpoint of mouseOver. In browser I can see that element is  hovered.

**Comment by aik099** [comment]
Can you please create minimalistic example of HTML and PHP (test) that can reproduce the problem?

**Comment by gamretsky** [comment]
Very interesting situation, minimalistic example of HTML works correct but in real page doesn't work. Trying to understand why it's happens, maybe because we are using ajax on hover.

**Comment by aik099** [comment]
If that is the case, `waitFor` method can help:

```php
$clickMe = $container->waitFor(function () {
    return $this->find(...);
});

```
That will get element when it appears in the document.

**Comment by aik099** [comment]
@gamretsky , ping.

**Comment by gamretsky** [comment]
@aik099 pong, in simple example works correct and this code 
[code]
$clickMe = $container->waitFor(function () {
    return $this->find(...);
});
[/code]
doesn't work too (( I think it's out html specific

**Comment by aik099** [comment]
That's really strange. I presume, that element is there and you can see 100% of it (you can check by looking at Selenium opened browser window) at moment, when test code calls Mink to act on it. Is it?

**Comment by aik099** [comment]
Maybe you can somehow arrange minimalistic test case, that can be used to reproduce the problem with all the JS/CSS/HTML needed, say on JsBin or JsFiddle?

**Comment by aik099** [comment]
And I suppose you closed this issue by mistake, because it seems that for you problem is still there and I'm willing to help out fixing it once I can reproduce it locally.

**Comment by gamretsky** [comment]
I closed this issue because it's our local problem. We are testing it in browser,  I see by myself that element is visible in browser window. When we make simple example it's works correct. We are left task for the best times because it's not priority. Thank's for help )
