### ISSUE TITLE
Proposal: No Selenium, fully native PhantomJS driver

### ISSUE THREAD

**Issue by jcalderonzumba** [minkphp/Mink#654]
The idea of this issue is to discuss the recent work i've been doing due to needs in my company and our decision to opensource the result.

The main point is to talk about whether it makes sense for this new driver to be "official" or to keep it as and Extension.

As of today since we did not want to change or fork anything we decided to implement this via an extension.

Find the work in: 

https://github.com/jcalderonzumba/MinkPhantomJSDriver

FAQ: 

1) Yes, it has unit tests.
2) Yes, it runs the integration tests against the driver suite.
3) It's using CI via travis to avoid breaking things when we are not supposed to.
4) Tested against phantomjs 1.9.8 but our company runs phantoms 2.0.1 with our own custom binary build. Is fair to say it works for both.

**Comment by aik099** [comment]
There was a discussion some time ago in #69 about writing separate driver for PhantomJS. But since, thanks to GhostDriver, PhantomJS can be used through MinkSelenium2Driver we haven't actually implemented it.

What are the benefits between Mink driver, which uses PhantomJS API and using PhantomJS via WebDriver?

**Comment by jcalderonzumba** [comment]
This driver that we / I wrote was due to some limitations on selenium based phantomjs driver, we needed to have a Yes on everything described here: http://mink.behat.org/en/latest/guides/drivers.html#driver-feature-support.

Also we wanted to have more "power" in terms of controlling the browser, with our approach we do not depend on GhostDriver or Selenium and new features can be easily plugged into the phantomjs code and therefore in the driver.

Regarding speed, i would have to share some data but when we changed from our selenium phantomjs based tests to our current one we gain from 20% to 25%.

**Comment by aik099** [comment]
Looking at the https://github.com/jcalderonzumba/MinkPhantomJSDriver repo I can tell few things:

1. it's a mix of several components (actual driver, helper classes to interact with PhantomJS, Behat extension)
2. integration code with MinkExtension
3. other stuff, like twig

Here are my concerns:

1. Behat-specific part should in a separate repo, because people can use driver with Mink only and not use Behat at all.
2. Also I'm not sure that introducing Twig as a dependency to replace a few variables in JS files is wise move.
3. Heavy trait usage makes this driver PHP 5.4+ only, but Mink itself isn't. I'm not sure why traits are used at all if they are included all together and only once in main driver file.
4. The namespace is quite confusing: `Behat\PhantomJSExtension\Portergeist\Browser`.

* If `Portergeist` is the vendor and `PhantomJSExtension` is product name, then namespace should be `Portergeist\PhantomJSExtension\Browser`.
* The `PhantomJSExtension` is also wrong if we're looking at what namespaces are used for other driver (they at least have `Driver` in it), but I guess this is due behat extension + driver mix in same repo.

**Comment by jcalderonzumba** [comment]
@aik099 thanks a lot for all your comments, they are as they should, precise and right to the point, 

4)The point 4 it makes a lot of sense seeing with other set of eyes, Nothing is closed as we are using this as beta thing for our stuff, that can be improved or revisited to fit a better namespace patterns.

3) as for the Traits parts, at least for the "Browser" component we wanted to separate and have Trait for specific logic related to different part, for example BrowserScriptTrait only deals with the browser commands related to javascript and native phantomjs things. We made this approach to avoid having one big class that does all the browser logic, as correct me if im wrong but we don't have multiple inheritance in PHP. So Traits was a way to "separate" into pieces of logic with the mind of new parts in the future as our browser commands can increase.

2) The twig part was our way to leave the door open for people in the future to add any kind of javascript related thing. As of now is true that only evaluates two or at most three variables but we wanted to avoid big chunks of pure javascript code inside pure PHP code. 
We can have a discussion about this but is more of a look into the future of custom made scripts to control things via the browser we have built inside phantomjs.
Example: Lets say that you want to check something in your tests but the best way might be to just check it via the "browser", then you write your test with javascript code that has access to even some internals of the phantomjs javascript part, then you just call $driver->execute or $driver->evaluate.

1) You are talking about the extension right?, we were not sure about how to approach all of this and made one thing for all, the Mink Driver, the Behat extension, the helper classes that allow the driver to talk to our custom made phantomjs browser scripts.

Once again, thanks a lot for taking the time to share your comments and concerns. I really appreciate it and it will help us and me specifically as i am the main maintainer of this.

Lets keep the discussion open and hope for more insights and comments. I will summarise the action points to follow with our approach as soon as I have several comments, suggestion, improvements, etc.

**Comment by aik099** [comment]
> 3) as for the Traits parts, at least for the "Browser" component we wanted to separate and have Traits for specific logic related to different parts, for example BrowserScriptTrait only deals with the browser commands related to javascript and native phantomjs things. We made this approach to avoid having one big class that does all the browser logic, as correct me if im wrong but we don't have multiple inheritance in PHP. So Traits was a way to "separate" into pieces of logic with the mind of new parts in the future as our browser commands can increase.

That's what currently each Mink driver class is - one large class with different functions. I guess that's ok.

> 2) The twig part was our way to leave the door open for people in the future to add any kind of javascript related thing. As of now is true that only evaluates two or at most three variables but we wanted to avoid big chunks of pure javascript code inside pure PHP code.

In other drivers we either use external JS files and do an `str_replace` on their content or just use HEREDOC for smaller pieces.

> Example: Lets say that you want to check something in your tests but the best way might be to just check it via the "browser", then you write your test with javascript code that has access to even some internals of the phantomjs javascript part, then you just call $driver->execute or $driver->evaluate.

I understand, that goal was to easy management of large JS code pieces. Usually Mink leaves that up to the developer (whoever will use Mink) to deal with that according to the use case. Internally, in some drivers, we're using HEREDOC or external JS files + `str_replace` to deal with it.

> Lets keep the discussion open and hope for more insights and comments. I will summarise the action points to follow with our approach as soon as I have several comments, suggestion, improvements, etc.

Sure. Thanks for your quick reply.

**Comment by stof** [comment]
> That's an interesting topic because before I haven't seen any "new driver" contributions, that would add itself to MinkExtension. @stof , how this is usually done?

See the Symfony2Extension. It is doing precisely that (and we added an extension point in Behat 3 extensions just to allow that actually)

**Comment by jcalderonzumba** [comment]
@stof @aik099 We followed the Symfony2Extension to create our own since we saw no other way to add the new driver to MinkExtension.

For the moment our extension is super dumb, it just registers the driver into the factory stuff. We are not doing anything complicated as the driver only needs the host where the phantomjs browser is.

**Comment by stof** [comment]
@jcalderonzumba can you explain why you replaced some of the driver tests by your own ones ? This looks weird to me. The goal of using the same testsuite is precisely to ensure that the different drivers work the same way.

**Comment by jcalderonzumba** [comment]
@stof 

Most of the replacement we had to do was due to a limitation of: http://phantomjs.org/api/webpage/property/content.html. 
This does not returns the real data that you send by the browser but something similar, in most cases is 100% the same, but sometimes when you don't send HTML as in some tests you have then the behaviour makes your driver-suite not to pass therefore we added our own.

Example in your tests: (StatusCodeTest)
```php
        $this->assertEquals('Sorry, page not found', $this->getSession()->getPage()->getContent());
```
For phantomjs the html of this is different and therefore the equals assertion fails so we had to replace it with getText().

Most of the changes are due to this getContent() reason when in the tests you send only plain text.

The other "big" change we had to do is also a limitation in the way we can evaluate scripts via phantomjs (we need to figure out what can we do to improve this "limitation").
```php
return array(
            array('1 + 1'),
            array('1 + 1;'),
            array('return 1 + 1'),
            array('return 1 + 1;'),
            array('function () {return 1+1;}()'),
            array('(function () {return 1+1;})()'),
            array('return function () { return 1+1;}()'),
            array('return (function () {return 1+1;})()'),
        );
```
For us some of those things return javascript errors and since is a single test we did not want just to skip it so we created our custom test with the ones that work.

In the end, this custom tests are there to continue checking that the browser does what its expected within the current limitations.

**Comment by stof** [comment]
Regarding the JS evaluation script, this test is precisely here to ensure that all drivers support the same ways to write JS. If you look at existing drivers, they all have to perform some changes to be able to support all of them. Making the testsuite pass by removing some tests is actually a lie.

Regarding the usage of traits, I also find it weird: each trait is relying on properties defined in the class using them, which means they are absolutely not reusable. This tends to defeat the purpose of traits. And you still end up with one class doing all the work, even though you split it across several files.

Regarding the organization, it would indeed be a good idea to separate the Mink driver, the Poltergeist layer and the Behat extension in separate packages.
What is your plan regarding this code ? do you prefer maintaining it under your own account and vendor name (in which case the top-level namespace should indeed be changed) or do you want it to become an official driver in the minkphp organization (with you as a maintainer as we don't want to add official drivers and then seeing their maintainers vanish leaving @aik099 and me in charge of all the maintenance, even though we will of course help for the maintenance) ?
Note that if it moves to minkphp, the Behat integration question will be solved easily: the driver factory would be moved to the MinkExtension itself. For the Poltergeist layer, it would have to live in a separate package added as a dependency of the driver (as done for the MinkSelenium2Driver and the webdriver library for instance).

and btw, there is a way to use PhantomJS 2 on Travis: https://github.com/minkphp/MinkSelenium2Driver/blob/7c96892dfce83b9bbf1f521262c2d869d618aea7/bin/run-phantomjs.sh and https://github.com/minkphp/MinkSelenium2Driver/blob/7c96892dfce83b9bbf1f521262c2d869d618aea7/.travis.yml#L16-17
It will become even easier after the next environment upgrade on Travis as PhantomJS 2 will be available in the VM directly and we will just have to adjust the call to use it

**Comment by jcalderonzumba** [comment]
@stof 
> Regarding the JS evaluation script, this test is precisely here to ensure that all drivers support the same ways to write JS. If you look at existing drivers, they all have to perform some changes to be able to support all of them. Making the testsuite pass by removing some tests is actually a lie.

Yes indeed is a lie, we have to (is on my TODO list, make the adjustments to allow the scripts to run accordingly), as for the moment at least we have some tests to check javascript evaluation.

> Regarding the usage of traits

Let us come back to that, i will also discuss it with my team because indeed not even myself ended up fully happy with the Trait separation result, but also having a big class is just something that makes my eyes cry.

> and btw, there is a way to use PhantomJS 2 on Travis:

Thanks a lot it's on my TODO list to add a travis matrix test with combinations of PHP + phantomjs version.

> Regarding the organization, it would indeed be a good idea to separate the Mink driver, the Poltergeist layer and the Behat extension in separate packages.

Is the first action point i will start working on, a proper separation between driver, poltergeist layer and behat extension.

> What is your plan regarding this code ?

I want it to be available to the users if it fits their needs, i will be a maintainer as i believe in the project and is not likely that i will abandon the code as is being used by our company and also in personal projects so a lot of improvements will be done in the short, mid term.

Being official is a nice idea as the reach to users will be greater than as an extension and driver outside of the core of Mink.

Let me first take actions on all of your comments, do a proper separation, after your comments and @aik099 ones i think i have a pretty good idea what to do, and it goes like this: 

* Poltergeist layer (or GastonJS as we call it internally) will be moved to a different package.
* Mink driver will use this new packages as a dependency
* Mink driver will be moved to Behat\Mink\Driver namespace (is that correct?) and different package.
* Mink extension will be moved to a different package and will use the driver as a dependency.

Once all the action points defined above are done let us decide the move as an official part of Mink, i think that would give the driver a lot of visibility and if such decision is taken be assured that i will be maintaining such driver.

Let me know your thoughs on the ideas to implement.

**Comment by stof** [comment]
if you want it to become official, the driver should indeed be moved to the ``Behat\Mink\Driver`` namespace. If you prefer keeping it on your own, use your own namespace.
For the Behat extension, it is a matter of opening a PR on the existing MinkExtension to add the new driver factory.

Btw, another step to make it official will be to make a PR to the mink documentation to add the driver :)

I'm totally OK making it an official driver. I guess the decision about that is on your side now (unless @aik099 is against it).

**Comment by aik099** [comment]
I'm OK with either driver location. I totally want to see that 20% speed increase compared to Selenium. Right now using Selenium is faster then PhantomJS over WebDriver, which is really strange.

**Comment by jcalderonzumba** [comment]
Cool, i will start to act upon all the discussed topics, I will keep you posted on the status of such actions.

Again thanks for all your valuable input on this project.

**Comment by jcalderonzumba** [comment]
@stof @aik099 Just to ping and keep the topic alive, there are new changes with some of the discussed topics. 

The first steps have been done (namespace changes) in order for a future move into different packages.

**Comment by stof** [comment]
@jcalderonzumba I suggest you to split the Behat integration into a separate package. Once it is done, we could look into adding a link to your driver in the official documentation

**Comment by stof** [comment]
ah no, there is another thing to do before: stopping to replacing driver-testsuite tests with your modified version to pretend that the testsuite is passing while it actually has a different behavior.

**Comment by stof** [comment]
Closing this as PhantomJS is not maintained anymore.
