### ISSUE TITLE
The "NodeElement::hasClass" doesn't support new lines

### ISSUE THREAD

**Issue by aik099** [minkphp/Mink#657]
In HTML it's allowed for css classes, listed in `class` html attribute to be separated by:

* any whitespace (not space specifically)
* any number of whitespace (not single one)

The `NodeElement::hasClass` method (see https://github.com/minkphp/Mink/blob/master/src/Element/NodeElement.php#L142) expects class names to be separated by single space. Therefore in the following CSS classes won't be properly detected:

```html
<div class="
one
two

three
"></div>
```
Yeah, some frameworks do generate such HTML.

**Comment by stof** [comment]
can you provide a fix ?

**Comment by aik099** [comment]
I'll see what I can do on this week.

**Comment by aik099** [comment]
PR created. Ready for testing.
