### ISSUE TITLE
Selenium IDE case files support

### ISSUE THREAD

**Issue by dav-m85** [minkphp/Mink#660]
If there is a way for Mink to play native [Selenium IDE](http://www.seleniumhq.org/docs/02_selenium_ide.jsp) test case files (the one in HTML)?

I've came across a plugin that exports directly to php, but I would love to see something like this:
```php
$session = new \Behat\Mink\Session($driver);
$session->start();
$session->playSeleniumIDECase("my-case.html");
```

My understanding is that such a function would not be that difficult to write, as Mink's scope overlaps Selenium IDE commands.

Maybe I'm missing something here, a better way of achieving this (Mink IDE ?), or a simple shortcut to get non tech user to write quick and dirty tests with little tech intervention. Selenium is achieving this, but in my sense lacks what is needed to correctly setUp cases.

Answer could interest @ianmoone

**Comment by aik099** [comment]
I thought Selenium IDE was long dead :wink: Anyway to my knowledge:

* MinkSelenium2Driver don't have support for that
* Mink as being cross-driver friendly surely won't have any driver-specific methods (e.g. that work with Selenium only)

Maybe this can be implemented like a stand-alone tool/repo that provides a helper library to:

* parse given Selenium IDE recoding
* return back PHP code for Mink

**Comment by stof** [comment]
I agree with @aik099 here. This is not something which can be in Mink itself. It might be possible to write a library on top of Mink to do it though.
In this case, the API would just end up looking like this for instance:

```php
$session = new \Behat\Mink\Session($driver);
$session->start();

$seleniumIDE = new MinkSeleniumIde($session); // this is the class you need to implement
$seleniumIDE->playSeleniumIDECase("my-case.html");
```

In any case, I'm not going to try to implement this (I have no interest in using Selenium IDE).

And the official Selenium documentation makes me think I'm right when I say it is out of our scope: http://www.seleniumhq.org/docs/01_introducing_selenium.jsp#selenium-ide and http://www.seleniumhq.org/docs/01_introducing_selenium.jsp#choosing-your-selenium-tool
