### ISSUE TITLE
All driver repos should be tested against PHP 7

### ISSUE THREAD

**Issue by stof** [minkphp/Mink#672]
- [x] Mink
- [x] BrowserKitDriver
- [x] GoutteDriver
- [x] Selenium2Driver
- [x] ZombieDriver
- [x] SahiDriver
- [x] SahiClient

**Comment by stof** [comment]
Mink and ZombieDriver actually still allow failures on PHP 7

**Comment by stof** [comment]
@aik099 we should also disallow failures on PHP 7 IMO

**Comment by aik099** [comment]
> @aik099 we should also disallow failures on PHP 7 IMO

Absolutely.

**Comment by aik099** [comment]
I've created PR for removing `allow_failures` for PHP 7 and also one that makes Goutte driver tested on PHP 7 as well, because it wasn't.

**Comment by aik099** [comment]
And I've created another one for BrowserKit drivers because it also wasn't tested on PHP 7 at all.

Should I create one for SahiClient and SahiDriver as well?

**Comment by stof** [comment]
Yeah, I would do it (PHP 7 is the current stable after all)

**Comment by aik099** [comment]
Also we use `7.0` in some repos and `7` in other repos in `.travis.yml`. It's recommended to use `7.0` consistently for accidentally not to test for `7.1` when it comes out.

**Comment by aik099** [comment]
PR sent for SahiClient and SahiDriver as well.

**Comment by stof** [comment]
> lso we use 7.0 in some repos and 7 in other repos in .travis.yml. It's recommended to use 7.0 consistently for accidentally not to test for 7.1 when it comes out.

I agree with you

**Comment by stof** [comment]
@aik099 do you know in which repo we use 7 instead of 7.0 ?

**Comment by aik099** [comment]
In these:

* MinkZombieDriver
* MinkSelenium2Driver

**Comment by aik099** [comment]
@stof , should I send PRs with PHP version change from `7` to `7.0` or you already have them in works, but haven't pushed yet?

**Comment by stof** [comment]
Please open PRs. I haven't worked on them

**Comment by aik099** [comment]
Here you go:

* https://github.com/minkphp/MinkZombieDriver/pull/156
* https://github.com/minkphp/MinkSelenium2Driver/pull/234
