### ISSUE TITLE
Auto-start session on "->visit(...)" call

### ISSUE THREAD

**Issue by aik099** [minkphp/Mink#678]
Currently if somebody attempts to do a `$session->visit(...);` call without calling `$session->start()` upfront, then this will ends up in exception.

To help out users I propose to auto-start session (only if not started already) inside `$session->visit(...)` method before any existing code.

**Comment by aik099** [comment]
It might also be a good idea to remove code, that auto-starts session on 1st query from `Mink::getSession` method (see https://github.com/minkphp/Mink/blob/master/src/Mink.php#L115-L118) because it will prevent complex object construction that need session eventually, but don't immediately use it.

**Comment by LogansUA** [comment]
:+1: Agree with second, I have a problem when i do like that:
```
$this->mink->getSession()->start();
```
Because i'm starting zombie session twice i have an error that is this port is already in use. Found it after hour of debugging.

**Comment by aik099** [comment]
@LogansUA , the mentioned `Mink::getSession` method always will auto-start session, so you'll never need to start it by hand.

**Comment by aik099** [comment]
PR is created, ready for review.
