### ISSUE TITLE
Inconsistent behavior of "Session::getCurrentUrl" in different drivers

### ISSUE THREAD

**Issue by aik099** [minkphp/Mink#679]
A lot of people are comparing current page url (obtained via `$session->getCurrentUrl()`) with desired url without even checking if a session was started.

If session isn't started upfront, then doing so (calling `getCurrentUrl` method) will:
- result in different Fatal Errors for driver if this was first executed test
- url opened last in that session (because we're doing soft reset and not changing current page url after test ends)

I'm not saying that each `Session` class method should detect if session is started, but at least `getCurrentUrl` method should return `null` when session isn't started.

**Comment by stof** [comment]
Well, calling it before the first request is explicitly documented as an unsupported behavior. We should throw an exception rather than fatal errors though.

**Comment by aik099** [comment]
OK. Closing.

**Comment by stof** [comment]
Drivers for which we get a fatal error should be fixed though (fatal errors make it hard to understand failures). Do you know which drivers are triggering fatal errors instead of exceptions ?

**Comment by aik099** [comment]
## Throws `DriverException`

1. MinkZombieDriver - throws `DriverException` due to `toString` method used on non-object
2. MinkBrowserKitDriver - throws nice `DriverException`
3. MinkGoutteDriver - throws nice `DriverException`

## Doesn't throw anything or result in Fatal Error

1. MinkSelenium2Driver - doesn't throw exception or fatal error
2. MinkSeleniumDriver - doesn't throw exception or fatal error
3. MinkSahiDriver - doesn't throw exception or fatal error

**Comment by stof** [comment]
fatal errors should be avoided indeed (well, SeleniumDriver is deprecated already, so no need to care).
