### ISSUE TITLE
Fatal Error, when running driver test suite on PHP 7

### ISSUE THREAD

**Issue by aik099** [minkphp/Mink#684]
At least MinkZombieDriver build fails due Fatal Error on PHP 7 (see https://travis-ci.org/minkphp/MinkZombieDriver/jobs/102687778):

```
PHP Fatal error:  Uncaught Declaration of Behat\Mink\Tests\Driver\TestCase::onNotSuccessfulTest(Exception $e) should be compatible with PHPUnit_Framework_TestCase::onNotSuccessfulTest($e)
```

The signature on PhpUnit used for PHP 5:

```php
protected function onNotSuccessfulTest(Exception $e)
```

The signature on PhpUnit used for PHP 7:

```php
protected function onNotSuccessfulTest($e)
```

Our overridden method signature:

```php
protected function onNotSuccessfulTest(\Exception $e)
```

**Comment by aik099** [comment]
I can try removing typehint from overridden method signature. This would fix PHP 7 build, but I'm not sure if it won't break PHP 5 builds.

@stof , any ideas?

**Comment by stof** [comment]
it would break. Unfortunately, I don't know any way to make code compatible with both PHPUnit 4 and 5 when using this method.

**Comment by aik099** [comment]
Maybe we can use approach that https://github.com/nikic/PHP-Parser/blob/master/lib/PhpParser/Autoloader.php did:

* create 2 base classes named exactly the same, but:
 * having different `onNotSuccessfulTest` method declaration
 * stored in different files that PSR-0 or PSR-4 of Composer won't auto-detect
* via custom auto-loader class load one for PHP 7 and another for for PHP 5.x

**Comment by stof** [comment]
or just a file containing both class definitions inside a ``if/else``. We would have to find the right feature detection though

**Comment by aik099** [comment]
we can check if `Throwable` interface (see http://php.net/manual/en/class.throwable.php) is present. Problem is that the `onNotSuccessfulTest` is only indirectly related to PHP 7 or that interface.

We can also use reflection to see what typehint is used in base test case class.

**Comment by stof** [comment]
PHPUnit 5 requires PHP 5.6+, not PHP 7. We need to detect the PHPUnit version, not the PHP version.

**Comment by aik099** [comment]
Hopefully PHPUnit have it's version defined as a constant somehow, because otherwise this might be dead end since PHPUnit can be installed via PHAR or via Composer.

**Comment by stof** [comment]
@aik099 either that, or we would have to feature detect it instead of version detecting it.

**Comment by aik099** [comment]
What I initially suggested to look at `onNotSuccessfulTest` method declaration via reflection to see which one of classes to use on our side.

**Comment by stof** [comment]
I'm working on it. I'm going the version way, as it is easier here (reflection-based would require defining some variables for hold these stuff, which would end up being global variables as they would be outside classes)
