### ISSUE TITLE
zombie proxy setting

### ISSUE THREAD

**Issue by MojaveKid** [minkphp/Mink#690]
hi all.

im trying out Mink using Zombie driver. its possible to set a proxy for Zombie (according to Zombie doc: browser.proxy) but I cant seem to find how to set the proxy from Mink.

does Mink allow proxy setting for Zombie ?

**Comment by aik099** [comment]
There is a PR for MinkZombieDriver at https://github.com/minkphp/MinkZombieDriver/pull/154 . Once it's completed and merged you should be able to specify any Zombie option, including `proxy` during `ZombieServer` class instantiation as shown on https://github.com/minkphp/MinkZombieDriver page.

**Comment by MojaveKid** [comment]
understood.

for now, i just added 2 functions on my local copy of ZombieDriver.php

public function setProxy($proxy)
{
	$proxyEscaped = json_encode($proxy);
	$js = <<<JS
browser.proxy = $proxyEscaped;
stream.end();
JS;
        $this->server->evalJS($js); 
}  
    
public function setTimeout($timeout)
{
	$js = <<<JS
browser.waitDuration = $timeout;
stream.end();
JS;
        $this->server->evalJS($js);
}

**Comment by aik099** [comment]
That would work until you restart a session. For new session you need to call both methods again.

**Comment by aik099** [comment]
Closing, because it partially duplicates existing PR.

**Comment by historylife** [comment]
@aik099 please is there any doc how to use proxy ?
