### ISSUE TITLE
selectOption can choose wrong option if target is a substring of another option

### ISSUE THREAD

**Issue by davidscotson** [minkphp/Mink#692]
It appears that if a select contains options like "Advanced Widget" and "Widget" then trying to select the "Widget" will select the "Advanced Widget" instead. (note order is important, the code takes the first thing that contains, as opposed to exactly matches, the search string)

In src/Behat/Mink/Element/NodeElement.php, the following function:
`    public function selectOption($option, $multiple = false)`

will go wrong at the following line:

```
        $opt = $this->find('named', array(
            'option', $this->getSession()->getSelectorsHandler()->xpathLiteral($option)
        ));
```

In the latest version of the code this line has been simplified to:

`        $opt = $this->find('named', array('option', $option));`

but I believe the same issue will be present.

**Comment by davidscotson** [comment]
Possibly, this was fixed by the 1.6 change to prefer exact matches when using "named"

**Comment by davidscotson** [comment]
Having read some other bugs, I'm closing this on the basis that newer code shouldn't show this issue anymore.

**Comment by aik099** [comment]
Yes, in next Mink version the partial match behavior was changed into:

* try doing exact match first
* if exact match find nothing try doing a partial match

**Comment by stof** [comment]
@aik099 1.6 is not the next version. It is a previous version. 1.7 is already stable.

**Comment by aik099** [comment]
I mean `next` in relation to version, that @davidscotson uses currently.
