### ISSUE TITLE
Mink on TravisCI

### ISSUE THREAD

**Issue by daison12006013** [minkphp/Mink#698]
Hi, 

I'm getting a weird stuff error when running Mink on TravisCI.

Here's the raw:
[https://s3.amazonaws.com/archive.travis-ci.org/jobs/116528437/log.txt](https://s3.amazonaws.com/archive.travis-ci.org/jobs/116528437/log.txt)

And here's my .travis.xml:
[https://github.com/phalconslayer/slayer/blob/dev/.travis.yml](https://github.com/phalconslayer/slayer/blob/dev/.travis.yml)

On my local, I tried to call my builtin web, and executed my PHPUnit, all things is working fine on my local, the test was able to create an account from a form. Able to go from page to the other page. 

However, when running it thru TravisCI, the registration form isn't working.

Here's my phpunit test file:
[https://github.com/phalconslayer/framework/blob/dev/tests/slayer/acceptance/WelcomeAndLoginAndRegisterTest.php](https://github.com/phalconslayer/framework/blob/dev/tests/slayer/acceptance/WelcomeAndLoginAndRegisterTest.php)

---

I also checked your travis test and I guess most of them are static file from this repo. I hope there is a clear way to test form submissions.

**Comment by aik099** [comment]
> Here's the raw: https://s3.amazonaws.com/archive.travis-ci.org/jobs/116528437/log.txt

That's a huge log file. Maybe you can just copy-paste relevant lines right in the task?

**Comment by aik099** [comment]
I guess the relevant error is:

```
[37m...PHP Fatal error:  Call to a member function toArray() on a non-object in /home/travis/build/phalconslayer/slayer/vendor/phalconslayer/framework/tests/slayer/acceptance/WelcomeAndLoginAndRegisterTest.php on line 104
```

I presume test code was changed since that log, because code calling `->toArray` that causing error is on 109 line now: https://github.com/phalconslayer/framework/blob/dev/tests/slayer/acceptance/WelcomeAndLoginAndRegisterTest.php#L109

Doesn't look like Mink related error at all. The `$user` variable isn't something you'd expect it to be and doesn't have `toArray` method, that is called.

**Comment by daison12006013** [comment]
@aik099, that's not the issue, the model User was able to create a record if you'll be running the test on your local it is probably working fine, the submission of form works well, the model is fully working fine.

My guess was in the submission of form, because upon clicking the submit button, there is a var_dump() that contains the model User count.

It seems there is a problem that prevents TravisCI when submitting a form thru POST.

If you will be checking Codeception, they're running builtin web php, while this repo only a static file supported.


I'll reproduce this on my local and will give you a screenshot.

**Comment by aik099** [comment]
The error I've picked from log file is what you think should not be happening?

And the link to test file is showing 404 to me now. Probably you've removed the branch.

**Comment by daison12006013** [comment]
Yes I removed the dev branch as I changed the settings of my composer, I also skipped the acceptance test on my project about this issue.

## On my Local:
![screenshot_1](https://cloud.githubusercontent.com/assets/4581415/13860681/8e83c10c-ecc4-11e5-9b7f-c6a89035393c.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/4581415/13860682/8e853190-ecc4-11e5-930d-d45d7f60de67.png)
![screenshot_3](https://cloud.githubusercontent.com/assets/4581415/13860683/8e88bbda-ecc4-11e5-946d-c8b330c16a02.png)
![screenshot_4](https://cloud.githubusercontent.com/assets/4581415/13860684/8e8b69a2-ecc4-11e5-94f5-451c8b030541.png)
![screenshot_5](https://cloud.githubusercontent.com/assets/4581415/13860713/b2c2200e-ecc4-11e5-8cec-73ba874b9ebb.png)


And here's the TravisCI:
[https://travis-ci.org/phalconslayer/slayer/builds/116643305](https://travis-ci.org/phalconslayer/slayer/builds/116643305)
![screenshot_6](https://cloud.githubusercontent.com/assets/4581415/13860887/901550f2-ecc5-11e5-800c-4f5973c1cc74.png)

The above image shows that the registered user count is 0, it must be 1, compare it to my local result.
---

## TravisCI able to do:
I have a database migration on my test suite and probably able to migrate, I also have a faker implemented while Phalcon Model I was able to write a new record.

I think this is a TravisCI + Mink issue, I don't know, as we don't have an actual web test on this project.

**Comment by aik099** [comment]
Try doing intermediate assertion instead. Instead of checking if user in fact was created assert that actions on the page were performed (e.g. form submission). The idea is find exact point in the process where it fails. Maybe it doesn't work on a specific PHP version used on Travis.

**Comment by daison12006013** [comment]
I'll probably checking the click function part and check the returned value instead, if there will be...

I'll gonna update this issue once found more.
