### ISSUE TITLE
Allow creating new document/session/DOM/client from another source

### ISSUE THREAD

**Issue by rudiedirkx** [minkphp/Mink#700]
My test sends an e-mail, which is caught by a test mail service, and then reads the e-mail to see if the right stuff was sent to the right person. I want to do several checks on the e-mail, and click on a link. The e-mail is always HTML (or we can assume it is).

Currently, there is only one state: the page you're on. I want to make a `@Given I am reading the last sent mail to :address` that opens the mail and exposes a new DOM document to "see" and "follow" on.

I can hack `Symfony\Component\BrowserKit\Client` to add a method `setCrawlerFromHtml($html)` which creates a crawler from the e-mail content, but hacking is bad, mkay. For full disclosure:

```
// In Symfony\Component\BrowserKit\Client:
public function setCrawlerFromHtml($html) {
  $this->crawler = $this->createCrawlerFromContent('http://example.com/', $html, 'text/html');
}

// In my FeatureContext:
$this->getSession()->getDriver()->getClient()->setCrawlerFromHtml($html);

// In myfeature.feature:
Given I am reading the last sent mail to "mgr3@org.nl"
When I follow "manager.email.invited.button"
```

Is there a way, or could you provide a way, for a Mink Context to create a session/client/page/DOM from HTML?

This might not be a Mink issue, but Mink contains the Session, Driver and Client, so I'll start here.

**Comment by rudiedirkx** [comment]
For full full disclosure, the following feature works, IF I hack that 1 method into `Symfony\Component\BrowserKit\Client`:

```
  @mail
  Scenario: New manager logs in from invite mail
    Given I am reading the last sent mail to "mgr3@org.nl"
    When I follow "manager.email.invited.button"
    And the url should match "^/users/\d+/accept/[A-Za-z0-9]+$"
    And I fill in the following:
      | firstname              | Manager                   |
      | middlename             |                           |
      | lastname               | Drie                      |
      | phone                  | 1234                      |
      | gender                 | m                         |
      | password               | test                      |
      | password_confirmation  | test                      |
      | accept-agreements      | 1                         |
    And I press "submit"
    Then I should be on the homepage
    And I should be logged in
```

which is pretty damn cool IMO.

**Comment by aik099** [comment]
So you want to act on email HTML as it was visited page HTML. Not sure that it's possible.

**Comment by aik099** [comment]
And this doesn't seem to be an issue with Mink, because you clearly dealing with Behat.

**Comment by stof** [comment]
-1 for this. Mink is a browser emulation library, so such feature does not make sense.

If you want to use the DomCrawler component of Symfony to extract the link from the email, do it outside Mink (using this component directly), and then use ``$session->visit()``

**Comment by rudiedirkx** [comment]
@aik099 Yes, I want to crawl the mail and act upon it. After clicking a link, it will continue in the 'browser'. I don't know which part is Mink and which part is Behat.

@stof I want to do all the browser things, but I want to start in the mail. I want to do more than extract the URL. I want all the "see" and "follow" etc functionality, because it's HTML, so it works like a browser. Copying ALL of it seems silly, because that's what Mink does perfectly.

Should I post this issue somewhere else? On Behat?

**Comment by stof** [comment]
@rudiedirkx As far as I understand, as soon as you use ``When I follow "manager.email.invited.button"``, you are not in the email anymore, but back in the browser. So using Mink after that makes perfect sense. What does not make sense is to use Mink itself to handle the email.

What I suggest you to do is to write things like that:

```gherkin
  @mail
  Scenario: New manager logs in from invite mail
    # This can be split into multiple steps if you prefer, it is a matter of readibility of the scenario
    When I follow the link of the email sent to "mgr3@org.nl"
    Then the url should match "^/users/\d+/accept/[A-Za-z0-9]+$"
    # ...
```

```php
class FeatureContext
{
    public function iFollowTheLinkOfTheEmail()
    {
        $emailHtml = // Get it from somewhere ... 
        $crawler = new Crawler($emailHtml);

        // Get the URI using the DomCrawler API (code finding the link element may need to be adjusted to your needs)
        $linkUrl = $crawler->selectLink('manager.email.invited.button')->link()->getUri();

        $this->getSession()->visit($linkUrl);
    }
}
```

**Comment by stof** [comment]
On a side note, your proposal does not make sense for Mink for several reasons:

- the state of Mink cannot be represented with only the HTML (we need to represent the response to a GET request on an URI, which means more info than just the HTML of the body of the response, as a response also has a status code and headers, and there is the requested URI)
- most drivers won't be able to implement what you suggest here, even if we forget about the previous point (only BrowserKitDriver would be able to hack such stuff)

**Comment by rudiedirkx** [comment]
> as soon as you use `When I follow "manager.email.invited.button"`, you are not in the email anymore

That's true, but before `I follow "abc"`, I'd like to `see "some text"` and `see "some other text"`. Mink has the relevant `@When` rules, so it'd be great if it were Mink checking those.

Both side note points make excellent sense, but my use case worked, so I wanted it =)

**Comment by rudiedirkx** [comment]
Can't I still do that: create my own Crawler, but use Mink's `When` logic to check a few rules programmatically?

**Comment by rudiedirkx** [comment]
So maybe this should be a Driver or (Symfony) Client issue? I want to fake a request and trick every class into thinking it's real. I'll manually provide the URL, status code, response headers etc. Where would I inject that fake request?

**Comment by stof** [comment]
Well, as said previously, faking a request like this would be totally impossible for almost all Mink drivers. So this makes it unsuitable for inclusion in the driver API. It is just out of the scope of Mink.

**Comment by aik099** [comment]
Closing. Suggested solution is to use `Crawler` component directly on mail body instead of involving Mink.
