### ISSUE TITLE
Allow manual session construction

### ISSUE THREAD

**Issue by aik099** [minkphp/Mink#706]
Right now new `Session` class instance creation is hidden within `Mink::getSession` class and there is no way affect created session in any way, e.g. add new selectors handler.

Any idea how to make it configurable.

Related issue: https://github.com/Behat/MinkExtension/issues/251

**Comment by stof** [comment]
this is totally false. The Mink object is unable to instantiate a session. It receives Session from the outside through dependency injection

**Comment by aik099** [comment]
My apologies. I always thought that it's creating sessions itself.

**Comment by stof** [comment]
this class is just a registry for session, making it easier to write code working with multiple sessions
