### ISSUE TITLE
elementAttributeNotExists

### ISSUE THREAD

**Issue by J7mbo** [minkphp/Mink#707]
Currently, if I would like to check that an element is disabled, I can use:

```
$this->assertSession()->elementAttributeExists('css', $element, 'disabled');
```

I would like to check that an element is no longer disabled. I expect to be able to use:

```
$this->assertSession()->elementAttributeNotExists('css', $element, 'disabled');
```

How valid do you think this use-case looks, and is there an alternative, preferred solution?

**Comment by stof** [comment]
Having the opposite assertion could indeed make sense. Can you send a PR implementing it (with tests) ?

**Comment by aik099** [comment]
Yes, new `elementAttributeNotExists` method can be helpful.

If we're talking about checking if element is disabled the HTML attribute comparison isn't right choice, because you can have element initially disabled, when page is rendered, but then element is enabled via JavaScript and assertion that looks at HTML attribute only won't pick that up.

**Comment by J7mbo** [comment]
I'll send in this PR I did anyway, and perhaps we can find a better solution for disabled specifically?

**Comment by aik099** [comment]
The #521 discussion already explains problem with disabled state checking. You can write your thoughts in there.

**Comment by J7mbo** [comment]
I completely forgot about that one still being there. I've deleted my branch and I'm starting fresh for this PR specifically, sorry for the confusion!

**Comment by aik099** [comment]
Then I guess #523 needs to be closed, because, since you deleted it's branch, you don't plan to continue it's development.

**Comment by J7mbo** [comment]
PR at #708

**Comment by J7mbo** [comment]
PR at #709 supersedes 708.
