### ISSUE TITLE
Mink website is gone

### ISSUE THREAD

**Issue by dzschille** [minkphp/Mink#715]
https://mink.behat.org/ is unknown:

```
$ ping mink.behat.org
ping: unknown host mink.behat.org
```

Where is the website or the documentation now?
Currently im using https://web.archive.org/web/20160610000426/http://mink.behat.org/en/latest/

**Comment by stof** [comment]
you can access the doc on http://mink.readthedocs.io/en/latest/

**Comment by stof** [comment]
mink.behat.org is also accessible for me, but not using HTTPS.

**Comment by dzschille** [comment]
Thanks for the answer!
Ah, yeah, the website is reachable again. Perhaps a temporarily DNS or server error? I tried to view the site not only from my desktop but also from my mobile, using another ISP.
Have a nice Sunday!
