### ISSUE TITLE
[RFC] Extract the driver testsuite to a dedicated package

### ISSUE THREAD

**Issue by stof** [minkphp/Mink#717]
Currently, the driver testsuite is maintained in the main Mik repo. but this leads to some weirdness:

- changes in the driver testsuite are done in the Mink repo, but do no impact the Mink CI (they are only about drivers)
- as we want the drivers to access it to run their tests, we cannot exclude it from the github archive, leading to the driver testsuite being installed in prod (hopefully not web accessible, but this is what triggers #689)
- drivers have to do weird things to be able to autoload classes in the driver testsuite (actually, this weird thing got moved to the driver testsuite itself, but then drivers have to use a PHPUnit bootstrap file from the vendor, which is also weird), as Mink is a dependency there and so ``autoload-dev`` cannot help us
- testing locally would be much easier if the driver testsuite could provide a script launching the necessary PHP webserver for fixtures (today, people must either find the right command manually, for instance by looking at our travis config, or configure a virtual host in their webserver), which could also remove the mandatory need for a webfixtures host (the phpunit.xml.dist in each driver could provide a value corresponding to the default value of this script instead of forcing you to provide a value). This is hard to do today, while a separate package could expose it as a composer bin script.

Most driver testsuite changes do no include any changes to Mink itself in the same PR. So the need for synchronisation of merges between Mink and the driver testsuite would be quite small, as this happens only in 1 case: when breaking BC in Mink (which should not happen outside of major versions). If we want to test a new feature, sync is not really needed. We just need to merge in Mink *before* merging in the driver testsuite (and bumping the driver testsuite min requirement for Mink in the PR using the new feature, or skipping the test).

So I see mostly advantages.
Note that this is also the approach used for the PHPCR testsuite (there is a package dedicated to it, and each implementation has a dev requirement on it).

what do you think @aik099 ?

**Comment by stof** [comment]
note that if we go this way, I suggest using ``mink`` as composer vendor instead of ``behat`` for the new package (migrating existing packages from ``behat/mink-*`` to ``mink/*`` would be left for later as it impacts users and I'm not sure this impact is worth it yet)

**Comment by aik099** [comment]
Sounds good. I remember that this topic was discussed in past as well.

> So I see mostly advantages.
Note that this is also the approach used for the PHPCR testsuite (there is a package dedicated to it, and each implementation has a dev requirement on it).

So each driver now would need to:

1. have new `mink/driver-tests` package as a dependency (alongside with `behat/mink`)
2. update test suite to point to main test suite in different sub-folder in `/vendor` folder

> drivers have to do weird things to be able to autoload classes in the driver testsuite (actually, this weird thing got moved to the driver testsuite itself, but then drivers have to use a PHPUnit bootstrap file from the vendor, which is also weird), as Mink is a dependency there and so autoload-dev cannot help us

Not sure if this would be improved, because we're just moving tests from one Composer package to another and autoloading stays as is.

> testing locally would be much easier if the driver testsuite could provide a script launching the necessary PHP webserver for fixtures

Not sure if creating some kind of universal script would be possible due diversity in workspace configuration for each developer, e.g.:

* for Windows users there are no `xvfb` to run 
* we can't pre-ship Selenium binary, because it's updated regularly and we can't update it in test package as well
* the developer might already have web server running and maybe doesn't want to start another one for tests
* if real display is used (not `xvfb`) then web server might be executed in VM and running Selenium server in there won't do any good

Lots of small details that makes automatic test environment configuration painful.

For Zombie driver you also need to have Zombie installed and we can't control that through Composer.

**Comment by stof** [comment]
> have new mink/driver-tests package as a dependency (alongside with behat/mink)

as a dev dependency to be exact.

> Not sure if this would be improved, because we're just moving tests from one Composer package to another and autoloading stays as is.

In this package, the testsuite will be the main code, not a development codebase. So it would be autoloaded by the main ``autoload`` rule (just like atoum or phpunit are autoloading their codebase, even though they are dev tools). And this means that drivers won't have to do weird hacks to register extra Mink folders in the autoloader anymore.

> Not sure if creating some kind of universal script would be possible due diversity in workspace configuration for each developer, e.g.:

I'm talking about a script exposing webfixtures in a webserver. I'm not talkign about a universal script running all dependencies of the testsuite. The selenium 2 driver would still ask to have a running selenium process. This is a separate process than the webserver anyway

> the developer might already have web server running and maybe doesn't want to start another one for tests

The question is whether the developer already has a webserver with a virtualhost pointing to the driver testsite web-fixtures folder. This is very unlikely to happen, except for you and me who are working on Mink regularly (and this is not happening for me on my new computer, I'm launching the PHP builtin webserver before running tests). Thus, this dev would need to have a virtualhost per Mink project they work on (as each of them will have a different setup of the driver testsuite, which might be at different version of the testsuite).
``./vendor/bin/mink-test-server`` is much easier to figuring out that ``php -S localhost:8000 -t vendor/behat/mink/driver-testsuite/web-fixtures`` is what you need to use.

And on a side note, the dev would still be free to use a virtual host in their webserver instead of using this command. My proposal would *add* a simple way to do it. It would not force you to use this simple way.

**Comment by aik099** [comment]
Agreed to all from above.

**Comment by stof** [comment]
OK, the repo is at https://github.com/minkphp/driver-testsuite, and it is registered on Packagist.
It also has Scrutinizer enabled to detect issues in the code (it does not have Travis, as there is no tests to run there).
And I'm opening a PR for the script.

I will work on updating driver repos before removing the driver testsuite from the Mink repo (so that driver CI setups are not broken). But we should stop accepting contributions to the driver testsuite here, redirecting them to the new repo instead.

**Comment by stof** [comment]
@aik099 I also suggest moving the Silex-based web-fixtures to the driver-testsuite repo, so that we can maintain it together with the normal fixtures. If you agree, I will do it before updating BrowserKitDriver.

**Comment by aik099** [comment]
> OK, the repo is at https://github.com/minkphp/driver-testsuite, and it is registered on Packagist.
It also has Scrutinizer enabled to detect issues in the code (it does not have Travis, as there is no tests to run there).
And I'm opening a PR for the script.

Already saw it. Did a review in there.

> https://github.com/minkphp/Mink/issues/717#issuecomment-250027317

Agreed.
