### ISSUE TITLE
[RFC] Automatically evaluate assertions of WebAssert for several seconds?

### ISSUE THREAD

**Issue by alexislefebvre** [minkphp/Mink#730]
Following a [previous discussion on Behat/MinkExtension](https://github.com/Behat/MinkExtension/pull/210), I'm working on implementing this logic in the current version of Mink. This causes massive changes in `WebAssert` (see [relevant PR on my fork](https://github.com/alexislefebvre/Mink/pull/3/files)).

The goal of these changes is to **put assertion in a callback that is passed to `waitFor()` so that assertion is evaluated during 5 seconds**. In other words, the test is retried during 5 seconds before failing. It adds some tolerance about time in the tests. For example, this is useful when tests load some content through AJAX and the content is not immediately available.

This new `timeout` argument may be used by [Behat/MinkExtension](https://github.com/Behat/MinkExtension), for example by defining the `timeout` value in a parameter.

**What do you think of this idea**? Do you think that these changes may be merged in Mink, with some rewriting?

Please keep in mind that:
- this doesn't work with PHP 5.3 yet, but it could be rewritten do add compatibility
- the default timeout value may be changed to `0`  in order to keep the current behaviour

**Comment by stof** [comment]
I don't think all assertions must do it automatically. It would slow down things to report failures for people *not* needing it (because they may not have AJAX loading changing the page).

Thus, it is common for a given assertion to span several calls to Mink (to find some element and the assert something on it for instance), and the waiting must then be done on the whole logic at once, not on each individual assertion.
So I don't think this is a good idea.

**Comment by lenybernard** [comment]
I think setting the default timeout value to 0 would avoid to change default behavior but will allow javascript session to use. Another PR in MinkExtension will then be required to allow wait (manually or automatically) when using selenium or a javascript session.

Does it make sense to you ?

PS. No more **And I wait 6 seconds** or a `FeatureMinkAjaxSubContext` ⏳

**Comment by stof** [comment]
@lenybernard this does not change the fact that waiting must not been performed on each assertion separately, but on the whole step (meaning that WebAssert is the wrong layer for that)

**Comment by alexislefebvre** [comment]
@stof So, should it take place in Behat/MinkExtension instead? What would be the right layer for that? Thanks.

**Comment by alexislefebvre** [comment]
@lenybernard implemented automatic assertions during 10 seconds (thanks to *spin functions*) in a really nice way: https://github.com/Troopers/BehatContexts/pull/18

So I'm closing this issue since the problem has been fixed.
