### ISSUE TITLE
Chrome puppeteer support

### ISSUE THREAD

**Issue by hkdobrev** [minkphp/Mink#741]
Hi!

I'm not sure if this is the right place to ask for this, but could you consider adding official extension for the newly released official library to manage headless Google Chrome - Chrome Puppeteer?

https://github.com/GoogleChrome/puppeteer

Many thanks!

**Comment by aik099** [comment]
It's not forbidden to have community supported Mink drivers. So you can easily create your own like was done with PhantomJS.

**Comment by stof** [comment]
Well, I don't think this would work for us: puppeteer is a high-level API, to be used when writing tests in Node. It is not something we can use to implement a Mink backend (at least not in a sane way).

The new thing about puppeteer is that it does not rely on WebDriver, but uses the DevTools protocol to communicate with Chrome instead.
This is something which could be done in PHP too, but it would mean reimplementing (part of) Puppeteer in PHP, not reusing Puppeteer.

It would be an interesting experiment (to see whether it is faster than using headless chrome with webdriver), but I don't have time to work on this. If you are interested in working on this, you can build an unofficial Mink driver outside the minkphp organization. If the experiment ends up working, we could then add it to official drivers.
If you build a new driver, look at existing drivers to see how to reuse the shared driver testsuite (and read https://github.com/minkphp/driver-testsuite)

**Comment by kasperg** [comment]
Perhaps [`dzentota/chrome-dev-tools`](https://github.com/dzentota/chrome-dev-tools) could be used as a foundation for a Chrome DevTools backend for Mink.

**Comment by rpkamp** [comment]
There is a mink driver for this now: https://packagist.org/packages/dmore/chrome-mink-driver

This is also already mentioned in documentation, composer suggests, etc. This ticket can be closed.

**Comment by aik099** [comment]
Thanks @rpkamp .

**Comment by mdio** [comment]
Just to clarify: The above mentioned [Mink driver](https://packagist.org/packages/dmore/chrome-mink-driver) works with (headless) Chrome but not with [Puppeteer](https://github.com/puppeteer/puppeteer).
