### ISSUE TITLE
POST Request

### ISSUE THREAD

**Issue by ztobs** [minkphp/Mink#745]
I have been trying to send a POST request on mink using goutte driver but i don't seem to see any working solution.
The `visit()` method takes only one argument which is the url.
In addition, i saw this somewhere but it doesnt work:
`$mink->getSession()->getDriver()->getClient()->request ('POST', "https://www...")`

**Comment by aik099** [comment]
The "Mink" isn't CURL for browser. It's supposed to do only things, that user can do on the page. If your URL is accessed via POST when a particular form is submitted, then you instead should do user action that triggers that form to be submitted.

**Comment by ztobs** [comment]
Unfortunately, goutte drivers don't support javascript, which make the submit button for the form not to work. Its more easier for me to collect the form data with `find()->getValue()` and send post request than tracing the script that triggers the submission and evaluating the javascript.

**Comment by aik099** [comment]
I see. Maybe you can use JS-enabled driver for a particular test. Or maybe change HTML/JS of the page to allow form to work in cases, when JS isn't enabled in the browser.

**Comment by ztobs** [comment]
I have zero access to the page source, and the environment i'm working on doesn't support selenium. I thought mink/goutte will work 100% from me, but now i'm deploying curl and injecting the headers from mink into it.
...Just hoping it works fine.

**Comment by ztobs** [comment]
Is there a way to get all the cookies rather than by specifying the cookie name?

**Comment by aik099** [comment]
> Is there a way to get all the cookies rather than by specifying the cookie name?

I see no method for that on `Session` object. I'm afraid you can't do that without messing with driver internals, which isn't recommended.

Maybe you can use things, like BrowserStack or SauceLabs which offer Selenium on their servers to test your website.

**Comment by ztobs** [comment]
Ok,
Thanks for the help so far. I will give your recommendations a trial.
