### ISSUE TITLE
метод getWebDriverSession в Behat\Mink\Driver\DriverInterface

### ISSUE THREAD

**Issue by danchukas** [minkphp/Mink#748]
**getWebDriverSession** - is accessed, but IDE not see it because this method not exist in interface.

Add please **getWebDriverSession** in **Behat\Mink\Driver\DriverInterface**.
we use it for _alert_, _confirm_:

```
class PopupContext extends RawMinkContext
{

    /**
     * @When I confirm the popup
     */
    public function confirm()
    {
        $this->getSession()->getDriver()->getWebDriverSession()->accept_alert();
    }



    /**
     * @When I cancel the popup
     */
    public function cancel()
    {
        $this->getSession()->getDriver()->getWebDriverSession()->dismiss_alert();
    }


    /**
     * @When I should see :message in popup
     *
     * @param string $message
     *
     * @throws \RuntimeException
     */
    public function assertPopupMessage($message)
    {
        $popup_message = $this->getSession()->getDriver()->getWebDriverSession()->getAlert_text();

        if ($popup_message !== $message) {
            throw new \RuntimeException("popup message \"$popup_message\" !== \"$message\" ");
        }

    }



    /**
     * @When I fill :value in popup
     *
     * @param $jsonText
     */
    public function setPopupText($jsonText)
    {
        $this->getSession()->getDriver()->getWebDriverSession()->postAlert_text($jsonText);
    }

}
```
___

Thanks for good library.

**Comment by aik099** [comment]
Please rewrite your issue in English.

**Comment by aik099** [comment]
Based on the code example I'm guessing you want to add methods for controlling `alert()`, `prompt()` and such dialogs in the browser. 

If that is so, then please read #158 about this topic. In there we haven't reached any consensus about possible cross-driver implementation.

**Comment by danchukas** [comment]
I rewrited in English.
yes, I wrote that topic.

**Comment by aik099** [comment]
Unfortunately adding `getWebDriverSession` to the `DriverInterface` won't be possible, because:

* it's a BC break
* only one driver has that method

I recommend using `/** @var ...` comments to fix IDE typehint like so:

```php
/** @var Selenium2Driver $driver */
$driver = $this->getSession()->getDriver();
```

Use FQCN or import driver class to make auto-complete on `$driver` work.

**Comment by stof** [comment]
getWebDriverSession is totally driver-specific. Only the driver based on WebDriver (i.e. Selenium 2+) has it.
Adding this in the interface would forbid having any other driver. So I'm closing it.
