### ISSUE TITLE
How to use 'xpath' as locator?

### ISSUE THREAD

**Issue by bartonhammond** [minkphp/Mink#758]
Is it possible to use `xpath` expressions for like `click`, or `find`.  I searched the docs and see only one result for `xpath`.

**Comment by aik099** [comment]
It's possible for `find`:

```php
$anchorsWithoutUrl = $page->findAll('xpath', '//a[not(@href)]');
```

Copied from http://mink.behat.org/en/latest/guides/traversing-pages.html?highlight=xpath .

**Comment by stof** [comment]
And `click` is not looking for any element. It clicks on the element on which you call the method (so you need to use `find` before it)

**Comment by bartonhammond** [comment]
Ok - thanks
