### ISSUE TITLE
Screeshot always blank white page

### ISSUE THREAD

**Issue by bartonhammond** [minkphp/Mink#759]
My screenshot is always blank white page (as shared below)

I notice there are 2 Chrome browsers and one is blank and the other has the site under test.  When I stop the processing w/  ` \Psy\Shell::debug(get_defined_vars(),$this);` and then execute the line manually `file_put_contents("/tmp/$arg1-image.png", $this->session->getDriver()->getScreenshot());      `  the browser window w/ the blank screen comes forward.  Why are there 2 browser windows and how can I force the screenshot against the correct window?
```
    /**
     * @When I go to the :arg1 page
     */
    public function iGoToThePage($arg1) {
        $this->current = $this->getPage($arg1);
        $this->current->open();
        sleep(1);
        file_put_contents("/tmp/$arg1-image.png", $this->session->getDriver()->getScreenshot());        
    }

```
Here's an example image

![home-image](https://user-images.githubusercontent.com/1282364/37314715-9a60a95a-2623-11e8-93d8-6a9e8eec6a08.png)

**Comment by aik099** [comment]
Can you please share your setup:

* used Mink version
* used Mink Driver and it's version
* if it's Selenium, then how you're running Selenium Server (real display or xvfb)
* if you're using the real display then it works correctly or not

**Comment by bartonhammond** [comment]
Sorry, here's dev section from composer:
```
    "require-dev": {
        "se/selenium-server-standalone": "^3.10",
        "facebook/webdriver": "^1.5",
        "behat/mink-goutte-driver": "^1.2",
        "behat/mink-selenium2-driver": "^1.3",
        "psy/psysh": "^0.8.17",
        "sensiolabs/behat-page-object-extension": "^2.1",
        "behat/mink-extension": "^2.3",
        "phpunit/phpunit": "^7.0",	
        "phpunit/phpcov": "^5.0",
        "phpunit/php-code-coverage": "^6.0",
        "wisnet/behatpom": "dev-master"
    },
    "repositories":[
```
for `selenium-server` I run `"vendor/bin/selenium-server-standalone  `
I don't understand the `real display or xvfb` - I guess it's real as I have a Chrome browser

**Comment by aik099** [comment]
So you're basically seeing mouse moving and how the clicks are happening in front of you, but attempt to take screenshot doesn't work.

I'm suspecting that this has something to do with Selenium 3.x server itself (maybe function not implemented properly) or issue with ChromeDriver.

Things, that might work for you:

1. use native Google Chrome integration VS via ChromeDriver of Selenium
2. try using Selenium Server 2.x
3. try using Firefox (the 40.x versions should work fine with Selenium 2.x)

**Comment by bartonhammond** [comment]
@aik099 What does this mean: 

> use  native Google Chrome integration VS via ChromeDriver of Selenium

Is this what I should do [https://packagist.org/packages/dmore/chrome-mink-driver](https://packagist.org/packages/dmore/chrome-mink-driver)

**Comment by bartonhammond** [comment]
@aik099 I figured it out.

In my Context I had the following:
```
  /**  @BeforeScenario   */
    public function before( $scope)  {
        $this->driver = new \Behat\Mink\Driver\Selenium2Driver('chrome');
        $this->session = new \Behat\Mink\Session($this->driver);
        $this->session->start();
}
```
But in my `behat.yml` I also have: 
```
    Behat\MinkExtension:
      browser_name: 'chrome'
      goutte: ~
      javascript_session: selenium2
      selenium2:
        wd_host: http://0.0.0.0:4444/wd/hub
        #wd_host: http://bhammond@wisnet.com:u0459a8738c4a60@hub.crossbrowsertesting.com:80/wd/hub
        capabilities: { "browser": "chrome", "version": "", "marionette": true, 'chrome': {'switches':['--start-maximized']}}
      base_url: https://uwce.dev
```
So that's why there was two browsers.  When I removed my `before/after Scenario`, only one browser was present.

Then in my `Context` I now have this:
```
use Behat\Behat\Context\Context;
use SensioLabs\Behat\PageObjectExtension\Context\PageObjectContext;
use Behat\Mink\Mink;
use Behat\MinkExtension\Context\MinkAwareContext;
class FeatureContext extends PageObjectContext implements MinkAwareContext {
```
So when I want to take the screenshot I have this:
```
        file_put_contents("/tmp/$arg1-image.png", $this->getMink()->getSession()->getDriver()->getScreenshot());        
```

And it works perfectly!  Thanks for your help @aik099
