### ISSUE TITLE
Interacting with Forms(sets the value of a form field) can somebody explain?

### ISSUE THREAD

**Issue by lynecker** [minkphp/Mink#761]
sorry if my question got wrong. i just don't understand what is explained by the documentation page (http://mink.behat.org/en/latest/guides/interacting-with-pages.html#interacting-with-forms)

i want to fill a login form and submit with mink, i think to use this element `NodeElement::setValue` but i don't understand to use that. can somebody give me a example codes?
This is the html form:

```
<div class="container">
   <label for="username"><b>Username</b></label>
   <input type="text" placeholder="Enter Username" name="username" required>
   <label for="password"><b>Password</b></label>
   <input type="password" placeholder="Enter Password" name="password" required>
   <button type="submit">Login</button>
</div>
```

**Comment by vincentmary** [comment]
Hello, 

 you can use $this->getSession()->getPage()->fillField('username', 'myusernamevalue'); 

you can also use setValue. Here's an example. 

$this->getSession()->getPage()->findField('username')->setValue('myusernamevalue');

Be sure that your context class extends MinkContext.

Hope it will help you

**Comment by OskarStark** [comment]
No feedback... should be closed
