### ISSUE TITLE
Fix PHP 5.4 and PHP 5.5 builds

### ISSUE THREAD

**Issue by aik099** [minkphp/Mink#776]
The PHP 5.4 and PHP 5.5 builds now fail, because Travis CI updated their VM image to Xenial, which doesn't support them. See:

* PHP 5.4: https://travis-ci.org/minkphp/Mink/jobs/536629418
* PHP 5.5: https://travis-ci.org/minkphp/Mink/jobs/536629419

Support representative from Travis CI suggested to add `dist: trusty` to relevant `.travis.yml` fragment in the build matrix to them work again.

**Comment by rpkamp** [comment]
Or, you know, just drop PHP 5 support, instead of spending time supporting archaic PHP versions :wink:
