### ISSUE TITLE
Error "Element not found with xpath, //html" after upgrading to Chrome 75

### ISSUE THREAD

**Issue by markbijl** [minkphp/Mink#778]
Hello everyone!

First of all let me just say I am a big fan of behat, mink, gherkin, selenium and... well... functional testing in general! The part I do every now and then struggle with, though, is the configuration of it all.

Today I performed my quarterly upgrades and ran into an issue. First I upgraded my Chrome to version 75.0.3770.90, upgraded chromedriver to 75.0.3770.90, upgraded selenium-server-standalone to selenium-server-standalone-3.141.59.jar, and all composer dependencies to:
```json
    "behat/behat": "^3.5",
    "behat/mink": "^1.7",
    "behat/mink-browserkit-driver": "^1.3",
    "behat/mink-extension": "2.2",
    "behat/mink-selenium2-driver": "^1.3",
    "behat/symfony2-extension": "^2.1",
```

Here is my behat.yml:
```
default:
  extensions:
    Liuggio\Fastest\Behat\ListFeaturesExtension\Extension: ~
    Bex\Behat\StepTimeLoggerExtension: ~
    Behat\Symfony2Extension:
      kernel:
        env: behat
        debug: false
    Behat\MinkExtension:
      files_path: 'features/_files'
      javascript_session: selenium_chrome_session
      default_session: symfony2
      browser_name: chrome
      symfony2: ~
      selenium2: ~
      sessions:
        selenium_chrome_session:
          selenium2:
            browser: chrome
            wd_host: http://localhost:4444/wd/hub
            capabilities:
              browserName: chrome
              browser: chrome
              extra_capabilities:
                chromeOptions:
                  prefs:
                    download.default_directory: "/tmp/behat/downloads"
                  args:
                    - "--window-position=0,0"
suites:
  ...
```

When I now run my test suite, though, I start getting the following error for the step 'And I should see X':
```bash
    And I should see "Pick Up Point"                                                                     # FeatureContext::assertPageContainsText()
      Element not found with xpath, //html
       (WebDriver\Exception\NoSuchElement)
```

Did anyone experience this issue before? Am I doing something wrong, or did I stumble upon an actual issue..?

Thanks in advance!
Mark

**Comment by aik099** [comment]
Maybe solution from https://github.com/minkphp/MinkSelenium2Driver/issues/293 (setting `w3c` option into `false` would help).

P.S.
Please report driver-specific issues in corresponding driver repository issue trackers.

**Comment by markbijl** [comment]
Dear Alex @aik099,

First of all thank you for your response! I'm going to try out that ```w3c``` setting for sure and let you know the outcome! Also my apologies for opening this issue in the wrong repository... I will close the issue here then, and open one in the [](https://github.com/minkphp/MinkSelenium2Driver) repository.

Kind regards,
Mark
