### ISSUE TITLE
Getting error while executing "vendor\behat\bin"

### ISSUE THREAD

**Issue by sd02test** [minkphp/Mink#784]
```
[Behat\Testwork\ServiceContainer\Exception\ExtensionInitializationException]   `Behat/MinkExtension` extension file or class could not be located."
```

![GitHub issue](https://user-images.githubusercontent.com/53756938/62458823-87f05800-b79b-11e9-8d32-a24a8bfb1fd2.jpg)

**Comment by kochen** [comment]
@sd02test this looks like an `autoload` issue

**Comment by stof** [comment]
I'm seeing a `/` in the error message, rather than a `\`. `/` is *not* the namespace separator in PHP.
