### ISSUE TITLE
mink crashes when visiting a local file

### ISSUE THREAD

**Issue by joachim-n** [minkphp/Mink#790]
I'm trying to track down a bug and so I made a static HTML file containing the bare minimum, and then started on a simple PHP script that would run Mink and load the HTML page.

Given it's static, I figured I'd load the file directly rather than go via the webserver.

This crashes. Here's my script, which is mostly based on the example code at http://mink.behat.org/en/latest/guides/session.html:

```
<?php

include "vendor/autoload.php";

// Choose a Mink driver. More about it in later chapters.
$driver = new \Behat\Mink\Driver\GoutteDriver();

$session = new \Behat\Mink\Session($driver);

// start the session
$session->start();

$session->visit('file:///Users/joachim/my-site/mink-test.html');
```

Backtrace is:

```
Fatal error: Uncaught GuzzleHttp\Exception\ConnectException: cURL error 7: Failed to connect to localhost port 80: Connection refused (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in /Users/joachim/my-site/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 185

GuzzleHttp\Exception\ConnectException: cURL error 7: Failed to connect to localhost port 80: Connection refused (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in /Users/joachim/my-site/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 185

Call Stack:
    0.0069     395576   1. {main}() /Users/joachim/my-site/minktest.php:0
    0.0564    1018760   2. Behat\Mink\Session->visit() /Users/joachim/my-site/minktest.php:13
    0.0564    1018760   3. Behat\Mink\Driver\GoutteDriver->visit() /Users/joachim/my-site/vendor/behat/mink/src/Session.php:148
    0.0564    1018760   4. Behat\Mink\Driver\Goutte\Client->request() /Users/joachim/my-site/vendor/behat/mink-browserkit-driver/src/BrowserKitDriver.php:144
    0.0570    1020832   5. Behat\Mink\Driver\Goutte\Client->doRequest() /Users/joachim/my-site/vendor/symfony/browser-kit/Client.php:407
```

Switching the URI for localhost:// works fine.

Composer reports my current version as dev-master, 1.7.x-dev; I assume this in the Composer output is the SHA I'm at:

```
source   : [git] https://github.com/minkphp/Mink.git a534fe7dac9525e8e10ca68e737c3d7e5058ec83
```

**Comment by aik099** [comment]
Such workflow (reading data from a local file) isn't supported by Goutte. Alternative solution, that I've found online: https://stackoverflow.com/questions/31154193/using-goutte-to-read-from-a-file-string

**Comment by joachim-n** [comment]
> Such workflow (reading data from a local file) isn't supported by Goutte

Fair enough. Could it maybe crash with a more meaningful message that says this?

**Comment by aik099** [comment]
Probably, but based on trace it's a long way from `visit` method call to actual exception happening in GuzzlePhp library. We could probably do a check for `file:///` in visited URL, but that is additional check on every `visit` method call, which performance-wise isn't very good.

You can send PR to Guzzle so that they'll report `file:///` url property, e.g. with `Unsupported protocol` error or something like that.

**Comment by joachim-n** [comment]
If I do this:

```
$client = new GuzzleHttp\Client();
$response = $client->request('GET', 'file:///Users/joachim/my-site/mink-test.html');
```

I get this:

```
Fatal error: Uncaught GuzzleHttp\Exception\RequestException: cURL error 1: Protocol "file" not supported or disabled in libcurl (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in /Users/joachim/my-site/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 186
```

which is fairy clear.

So it looks like the lack of a clear error is caused by how Goutte is calling Guzzle?

**Comment by aik099** [comment]
Maybe. You can try debugging and see where clear exception message is converted to confusing exception message.
