### ISSUE TITLE
DOMXPath::query(): Invalid expression

### ISSUE THREAD

**Issue by josegamboa** [minkphp/Mink#799]
Hi Guys,

I am new using Mink, it is an awesome tool, thanks a lot for supporting it:

I am looking for specific property value in a div that looks like this:

`<div data-prop-filters="[{filterKey:Category,filterValue:Mobile}]" data-component="Filter" dclass="component"></div>`
I am assertting the value like this:
`$web_assert->elementExists('xpath', '//div[@data-prop-filters="[{"filterKey":"Category","filterValue":"Mobile"}]"]');`
and 

`$web_assert->elementExists('xpath', '//div[@data-prop-filters=\"[{"filterKey":"Category","filterValue":"Mobile"}]\"]');`

But I am having this issue: **DOMXPath::query(): Invalid expression**, I am not sure if I am missing something or I am using the wrong function to validate that value.

**Comment by stof** [comment]
This is because your XPath is indeed invalid, due to the `"` in your attribute values inside a XPath literal written with double quotes.
The simplest solution here is to use single quotes for your literal:

```php
$web_assert->elementExists('xpath', '//div[@data-prop-filters=\'[{"filterKey":"Category","filterValue":"Mobile"}]\']');
```

There is nothing specific to Mink here, that's about how XPath works.

**Comment by josegamboa** [comment]
Hi @stof,

Thanks a lot for your help,  yes that was the problem, it is working fine now.
