### ISSUE TITLE
Fix latest release label

### ISSUE THREAD

**Issue by ruudk** [minkphp/Mink#800]
Looks like there is no new release, but there is, it's hidden. 
<img width="554" alt="Screenshot 2020-05-19 at 14 57 59@2x" src="https://user-images.githubusercontent.com/104180/82329189-368b1f80-99e1-11ea-8632-64452ff7f237.png">

@stof can you either remove the `latest` label from 1.7 or add it to 1.8.1 ?

**Comment by stof** [comment]
I created the github releases for the 1.8.0 and 1.8.1 tags. That was forgotten when releasing.
