### ISSUE TITLE
Feature: set basic auth after session start and reset

### ISSUE THREAD

**Issue by petarbasic** [minkphp/Mink#810]
Testing sites with basic auth set became an issue for us after some extensions updates. 
In particular, an extension was calling the session reset which effectively removes the pre-set basic auth credentials (header). 

It would be nice if mink session would support setting basic auth credentials and use them if they are set after session start & reset. 

I've created a PR that fixes the issue for us. Please take a look and let us know if it would make sense to support this.
PR: https://github.com/minkphp/Mink/pull/809

**Comment by fago** [comment]
This came up at jhedstrom/drupalextension#597 but would make sense to fix in mink actually.

**Comment by stof** [comment]
Well, the fact that resetting the session resets the basic auth is a feature, not a bug. This is what allows to keep Behat scenarios isolated without stopping the session entirely each time (which is costly in case of webdriver as it would stop and restart the browser for instance)

If the Drupal behat extension expects to be able to reset the session and having basic auth credentials preserved, I suggest that it stores them on its side and sets them again after the reset (according to the issue you linked, they seem to be doing that already for a cookie they want to keep).

**Comment by aik099** [comment]
@fago , I agree with @stof on this.

The Behat extension is a good place to actually maintain the session state. The corresponding `@beforeScenario` and such hooks could come in handy to do this.

I'll also close associated PR.
