### ISSUE TITLE
GET Request

### ISSUE THREAD

**Issue by augisbud** [minkphp/Mink#834]
Hello, I might be very much missing something in the documentation, however I'm having an issue where I want to visit a page 'https://example.com?TEST=DEV' however it's redirecting to 'https://example.com'

`$mink->getSession()->visit('https://example.com?TEST=dev');`

How should I approach the GET parameters?

I'm using the ChromeDriver if neccesary.

**Comment by aik099** [comment]
Hello,

Mink, as far as I remember, doesn't perform any redirects. Maybe your website is doing that?

Try showing `$_SERVER['REQUEST_URI']` on the visited to see if parameter actually is supplied by Mink.

Another wild guess: something if performing http->https redirect and looses all query string.

**Comment by augisbud** [comment]
You were right, the page somehow mishandled the GET request.
